# This configuration is to create a secret using which image would be pulled from the docker registry. This is a one-time activity per namespace. Please uncomment to create a new docker registry secrete.

#apiVersion: v1
#data:
#  .dockerconfigjson: eyJhdXRocyI6eyJwbGF0Zm9ybTEuaGNsZXRzLmNvbToxODQ0MyI6eyJ1c2VybmFtZSI6Imt1bWFyLnJhamUiLCJwYXNzd29yZCI6IlAjc3N3MHJkMjQ2IiwiZW1haWwiOiJrdW1hci5zaG9yYXZAaGNsLmNvbSIsImF1dGgiOiJhM1Z0WVhJdWNtRnFaVHBRSTNOemR6QnlaREkwTmc9PSJ9fX0=
#kind: Secret
#metadata:
#  name: <registry-secrets name>
#type: kubernetes.io/dockerconfigjson